# Generated by Django 4.2 on 2025-05-14 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carta', '0006_alter_category_id_alter_item_id'),
        ('cabins', '0011_cabin_review_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Fechas Disponibles',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabins.cabin')),
                ('dishes_order1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_item1', to='carta.item')),
                ('dishes_order2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_item2', to='carta.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
