# Generated by Django 4.2 on 2026-03-04 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de Reserva')),
                ('available', models.BooleanField(default=True, verbose_name='Habilitada')),
                ('cabin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cabins.cabin', verbose_name='Cabaña')),
            ],
            options={
                'verbose_name_plural': 'Habilitar Fechas',
                'unique_together': {('date', 'cabin')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabins.cabin', verbose_name='Cabaña')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation_date', verbose_name='Fecha de Reserva')),
                ('dishes_order1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_item1', to='carta.item', verbose_name='Menú 1')),
                ('dishes_order2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_item2', to='carta.item', verbose_name='Menú 2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Reservation_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField(verbose_name='Fecha de Llegada')),
                ('checkout', models.DateField(verbose_name='Fecha de Salida')),
                ('user_phone', models.CharField(blank=True, default='', max_length=15, verbose_name='Teléfono del Usuario')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('approved', models.BooleanField(default=False, verbose_name='Aprobar Solicitud')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Solicitudes de Reserva',
                'unique_together': {('date',)},
            },
        ),
    ]
