# Generated by Django 4.2 on 2025-05-14 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0011_cabin_review_show'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carta', '0006_alter_category_id_alter_item_id'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='cabin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabins.cabin', verbose_name='Cabaña'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation_date', verbose_name='Fecha de Reserva'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dishes_order1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_item1', to='carta.item', verbose_name='Menu 1'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dishes_order2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_item2', to='carta.item', verbose_name='Menu 2'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
