# Generated by Django 4.2 on 2025-05-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_date_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation_date',
            options={'verbose_name_plural': 'Fechas Disponibles'},
        ),
        migrations.RemoveField(
            model_name='reservation_date',
            name='cabin',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(verbose_name='Fecha de Reserva'),
        ),
    ]
