# Generated by Django 4.2 on 2025-05-14 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0006_alter_category_id_alter_item_id'),
        ('cabins', '0011_cabin_review_show'),
        ('reservations', '0004_alter_reservation_date_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_date',
            name='cabin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cabins.cabin', verbose_name='Cabaña'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation_date', verbose_name='Fecha de Reserva'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dishes_order1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_item1', to='carta.item', verbose_name='Menú 1'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dishes_order2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_item2', to='carta.item', verbose_name='Menú 2'),
        ),
        migrations.AlterUniqueTogether(
            name='reservation_date',
            unique_together={('date', 'cabin')},
        ),
    ]
