# Generated by Django 4.2 on 2025-06-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservation_date_cabin_alter_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation_date',
            options={'verbose_name_plural': 'Habilitar Fechas'},
        ),
        migrations.AlterField(
            model_name='reservation_date',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Habilitada'),
        ),
        migrations.AlterField(
            model_name='reservation_date',
            name='date',
            field=models.DateField(verbose_name='Fecha de Reserva'),
        ),
    ]
