# Generated by Django 4.2 on 2025-06-10 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0006_alter_reservation_date_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField(verbose_name='Fecha de Llegada')),
                ('checkout', models.DateField(verbose_name='Fecha de Salida')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Solicitudes de Reserva',
                'unique_together': {('date',)},
            },
        ),
    ]
