# Generated by Django 4.2 on 2025-06-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_reservation_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_request',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Aprobar Solicitud'),
        ),
        migrations.AddField(
            model_name='reservation_request',
            name='user_phone',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Teléfono del Usuario'),
        ),
    ]
