# Generated by Django 4.2 on 2025-04-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('image1', models.FileField(default='default_item_image', upload_to='Item_images', verbose_name='Imagen')),
                ('image2', models.FileField(default='default_item_image', upload_to='Item_images', verbose_name='Imagen')),
                ('image3', models.FileField(default='default_item_image', upload_to='Item_images', verbose_name='Imagen')),
                ('image4', models.FileField(default='default_item_image', upload_to='Item_images', verbose_name='Imagen')),
                ('image5', models.FileField(default='default_item_image', upload_to='Item_images', verbose_name='Imagen')),
                ('image6', models.FileField(default='default_item_image', upload_to='Item_images', verbose_name='Imagen')),
            ],
            options={
                'verbose_name_plural': 'Cabañas',
            },
        ),
    ]
