# Generated by Django 4.2 on 2026-03-04 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabin_image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('image', models.FileField(upload_to='cabin_images', verbose_name='Imagen')),
            ],
            options={
                'verbose_name_plural': 'Imagenes de Cabañas',
            },
        ),
        migrations.CreateModel(
            name='Cabin_service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Servicio')),
            ],
            options={
                'verbose_name_plural': 'Servicios de Cabañas',
            },
        ),
        migrations.CreateModel(
            name='Cabin_review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=0, verbose_name='Calificacion')),
                ('comment', models.TextField(blank=True, max_length=500, verbose_name='Comentario')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('show', models.BooleanField(default=False, verbose_name='Mostrar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comentarios de Cabañas',
            },
        ),
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('price', models.IntegerField(default=0, verbose_name='Precio Noche')),
                ('name', models.CharField(default='Cabaña', max_length=50, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Descripcion')),
                ('capacity', models.IntegerField(default=0, verbose_name='Capacidad')),
                ('images', models.ManyToManyField(blank=True, related_name='cabins', to='cabins.cabin_image', verbose_name='Imagenes')),
                ('reviews', models.ManyToManyField(blank=True, related_name='cabins', to='cabins.cabin_review', verbose_name='Comentarios')),
                ('services', models.ManyToManyField(blank=True, related_name='cabins', to='cabins.cabin_service', verbose_name='Servicios')),
            ],
            options={
                'verbose_name_plural': 'Cabañas',
            },
        ),
    ]
