# Generated by Django 4.2 on 2025-04-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabin',
            name='capacity',
            field=models.IntegerField(default=0, verbose_name='Capacidad'),
        ),
        migrations.AddField(
            model_name='cabin',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='cabin',
            name='name',
            field=models.CharField(default='Cabaña', max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='cabin',
            name='pets',
            field=models.BooleanField(default=False, verbose_name='Mascotas'),
        ),
        migrations.AddField(
            model_name='cabin',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Precio'),
        ),
        migrations.AddField(
            model_name='cabin',
            name='wifi',
            field=models.BooleanField(default=False, verbose_name='Wifi'),
        ),
    ]
