# Generated by Django 4.2 on 2025-04-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0002_cabin_capacity_cabin_description_cabin_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabin',
            name='image1',
            field=models.FileField(blank=True, default='default_cabin_image', null=True, upload_to='cabin_images', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='cabin',
            name='image2',
            field=models.FileField(blank=True, default='default_cabin_image', null=True, upload_to='cabin_images', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='cabin',
            name='image3',
            field=models.FileField(blank=True, default='default_cabin_image', null=True, upload_to='cabin_images', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='cabin',
            name='image4',
            field=models.FileField(blank=True, default='default_cabin_image', null=True, upload_to='cabin_images', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='cabin',
            name='image5',
            field=models.FileField(blank=True, default='default_cabin_image', null=True, upload_to='cabin_images', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='cabin',
            name='image6',
            field=models.FileField(blank=True, default='default_cabin_image', null=True, upload_to='cabin_images', verbose_name='Imagen'),
        ),
    ]
