# Generated by Django 4.2 on 2025-04-20 05:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0003_alter_cabin_image1_alter_cabin_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabin',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
