# Generated by Django 4.2 on 2025-04-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0004_alter_cabin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabin',
            name='image1',
            field=models.FileField(blank=True, default='default_cabin_image', null=True, upload_to='cabin_images', verbose_name='Imagen1'),
        ),
        migrations.AlterField(
            model_name='cabin',
            name='image2',
            field=models.FileField(blank=True, default='default_cabin_image', null=True, upload_to='cabin_images', verbose_name='Imagen2'),
        ),
        migrations.AlterField(
            model_name='cabin',
            name='image3',
            field=models.FileField(blank=True, default='default_cabin_image', null=True, upload_to='cabin_images', verbose_name='Imagen3'),
        ),
        migrations.AlterField(
            model_name='cabin',
            name='image4',
            field=models.FileField(blank=True, default='default_cabin_image', null=True, upload_to='cabin_images', verbose_name='Imagen4'),
        ),
        migrations.AlterField(
            model_name='cabin',
            name='image5',
            field=models.FileField(blank=True, default='default_cabin_image', null=True, upload_to='cabin_images', verbose_name='Imagen5'),
        ),
        migrations.AlterField(
            model_name='cabin',
            name='image6',
            field=models.FileField(blank=True, default='default_cabin_image', null=True, upload_to='cabin_images', verbose_name='Imagen6'),
        ),
        migrations.AlterField(
            model_name='cabin',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Precio Noche'),
        ),
    ]
