# Generated by Django 4.2 on 2025-04-30 05:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0005_alter_cabin_image1_alter_cabin_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabin',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='cabin',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='cabin',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='cabin',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='cabin',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='cabin',
            name='image6',
        ),
        migrations.CreateModel(
            name='Cabin_service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(blank=True, default='Servicio', max_length=50, verbose_name='Servicio')),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabin_service', to='cabins.cabin')),
            ],
            options={
                'verbose_name_plural': 'Servicios Cabañas',
            },
        ),
        migrations.CreateModel(
            name='Cabin_image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(blank=True, default='default_cabin_image', null=True, upload_to='cabin_images', verbose_name='Imagen')),
                ('cabin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabin_image', to='cabins.cabin')),
            ],
            options={
                'verbose_name_plural': 'Imagenes Cabañas',
            },
        ),
    ]
