# Generated by Django 4.2 on 2025-04-30 05:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0006_remove_cabin_image1_remove_cabin_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(blank=True, default='default_cabin_image', null=True, upload_to='cabin_images', verbose_name='Imagen')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Orden en que aparece esta imagen')),
            ],
            options={
                'verbose_name_plural': 'Imágenes de Cabañas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Servicio')),
            ],
            options={
                'verbose_name_plural': 'Servicios de Cabañas',
            },
        ),
        migrations.RemoveField(
            model_name='cabin_service',
            name='cabin',
        ),
        migrations.RemoveField(
            model_name='cabin',
            name='pets',
        ),
        migrations.RemoveField(
            model_name='cabin',
            name='wifi',
        ),
        migrations.AlterField(
            model_name='cabin',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Descripción'),
        ),
        migrations.DeleteModel(
            name='Cabin_image',
        ),
        migrations.DeleteModel(
            name='Cabin_service',
        ),
        migrations.AddField(
            model_name='cabinimage',
            name='cabin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cabins.cabin', verbose_name='Cabaña'),
        ),
        migrations.AddField(
            model_name='cabin',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='cabins', to='cabins.service', verbose_name='Servicios'),
        ),
    ]
