# Generated by Django 4.2 on 2025-04-30 06:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0007_cabinimage_service_remove_cabin_service_cabin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabin_image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('image', models.FileField(upload_to='cabin_images', verbose_name='Imagen')),
            ],
        ),
        migrations.RenameModel(
            old_name='Service',
            new_name='Cabin_service',
        ),
        migrations.AlterField(
            model_name='cabin',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Descripcion'),
        ),
        migrations.DeleteModel(
            name='CabinImage',
        ),
        migrations.AddField(
            model_name='cabin',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='cabins', to='cabins.cabin_image', verbose_name='Imagenes'),
        ),
    ]
