# Generated by Django 4.2 on 2025-05-08 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabins', '0008_cabin_image_rename_service_cabin_service_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabin_image',
            options={'verbose_name_plural': 'Imagenes de Cabañas'},
        ),
        migrations.CreateModel(
            name='Cabin_review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=0, verbose_name='Calificacion')),
                ('comment', models.TextField(blank=True, max_length=500, verbose_name='Comentario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comentarios de Cabañas',
            },
        ),
        migrations.AddField(
            model_name='cabin',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='cabins', to='cabins.cabin_review', verbose_name='Comentarios'),
        ),
    ]
