# Generated by Django 4.2 on 2025-05-08 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0009_alter_cabin_image_options_cabin_review_cabin_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabin_review',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creacion'),
            preserve_default=False,
        ),
    ]
