# Generated by Django 4.2 on 2025-05-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabins', '0010_cabin_review_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabin_review',
            name='show',
            field=models.BooleanField(default=False, verbose_name='Mostrar'),
        ),
    ]
