# Generated by Django 4.2 on 2026-03-04 15:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='Titulo', max_length=100, verbose_name='Titulo')),
                ('url', models.FileField(upload_to='Slider_images', verbose_name='Url')),
            ],
            options={
                'verbose_name_plural': 'Slider Principal',
            },
        ),
    ]
