# Generated by Django 4.2 on 2025-04-23 14:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image1', models.FileField(default='default_item_image', upload_to='Slider_images', verbose_name='Image1')),
                ('image2', models.FileField(default='default_item_image', upload_to='Slider_images', verbose_name='Image2')),
                ('image3', models.FileField(default='default_item_image', upload_to='Slider_images', verbose_name='Image3')),
            ],
            options={
                'verbose_name_plural': 'Slider Principal',
            },
        ),
    ]
