# Generated by Django 4.2 on 2025-04-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image4',
            field=models.FileField(default='default_item_image', upload_to='Slider_images', verbose_name='Imagen 4'),
        ),
        migrations.AddField(
            model_name='slider',
            name='image5',
            field=models.FileField(default='default_item_image', upload_to='Slider_images', verbose_name='Imagen 5'),
        ),
        migrations.AddField(
            model_name='slider',
            name='image6',
            field=models.FileField(default='default_item_image', upload_to='Slider_images', verbose_name='Imagen 6'),
        ),
        migrations.AddField(
            model_name='slider',
            name='image7',
            field=models.FileField(default='default_item_image', upload_to='Slider_images', verbose_name='Imagen 7'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image1',
            field=models.FileField(default='default_item_image', upload_to='Slider_images', verbose_name='Imagen 1'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image2',
            field=models.FileField(default='default_item_image', upload_to='Slider_images', verbose_name='Imagen 2'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image3',
            field=models.FileField(default='default_item_image', upload_to='Slider_images', verbose_name='Imagen 3'),
        ),
    ]
