# Generated by Django 4.2 on 2026-03-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='message',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Mensaje'),
        ),
    ]
