# Generated by Django 4.2 on 2025-04-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_slider_image4_slider_image5_slider_image6_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image7',
        ),
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.FileField(default='default_item_image', upload_to='Slider_images', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(blank=True, default='Titulo', max_length=100, verbose_name='Titulo'),
        ),
    ]
