# Generated by Django 4.2 on 2025-04-29 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0003_remove_slider_image1_remove_slider_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='image',
            new_name='url',
        ),
    ]
