# Generated by Django 4.2 on 2025-04-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0004_rename_image_slider_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='url',
            field=models.FileField(upload_to='Slider_images', verbose_name='Url'),
        ),
    ]
