# Generated by Django 4.2 on 2026-03-04 15:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50, unique=True, verbose_name='Categoría')),
                ('possition', models.IntegerField(default=0, unique=True, verbose_name='Posción')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'ordering': ['possition'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Descripcion')),
                ('price', models.IntegerField(default=0, verbose_name='Precio')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('image', models.FileField(default='default_item_image', upload_to='Item_images', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carta.category')),
            ],
            options={
                'verbose_name_plural': 'Carta Items',
            },
        ),
    ]
