# Generated by Django 4.2 on 2023-05-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='category',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='category',
            name='possition',
            field=models.IntegerField(default=0, unique=True, verbose_name='Posción'),
        ),
        migrations.AlterField(
            model_name='item',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Precio'),
        ),
    ]
