# Generated by Django 4.2 on 2023-05-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0002_item_description_alter_category_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['possition'], 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Carta Items'},
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.FileField(default='default_item_image', upload_to='Items_images'),
        ),
    ]
