# Generated by Django 4.2 on 2024-01-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0003_alter_category_options_alter_item_options_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(default='default_item_image', upload_to='Item_images', verbose_name='Imagen'),
        ),
    ]
